require:
  - rubocop-packaging

AllCops:
  NewCops: enable
  Exclude:
    - '.bundle/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - 'lib/string-direction.rb'

Metrics/BlockLength:
  ExcludedMethods:
    - configure
    - describe
    - context
    - shared_examples

Naming/FileName:
  Exclude:
    - 'lib/string-direction.rb'
    - 'spec/string-direction_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false
